---
title: "Pursue STEM Student Responses"
output:
  html_document:
    df_print: paged
    css: [xaringan-themer.css, pursue-stem-theme.css]
---

```{r, message=FALSE, echo=FALSE}
 knitr::opts_chunk$set(echo=F, message = F) 

library(tidyverse)
library(plotly)
library(emojifont)

colors = c(
    red = "#f34213",
    yellow = "#FFCA17",
    purple = "#43003F",
    white = "#FFFFFF"
  )

survey1 <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRiq9xggASJOtZCW1lxDO6snw5ViicSjt2nrAD_FWmvLRnQH45XkoRCGrJbHBal2V3TSY-nf43ZySYh/pub?output=csv")

```


# Getting started {.tabset}

## Duck check-in

```{r}
duck <- survey1 %>% 
  rename(n = 2) %>% 
  mutate(n = factor(n)) %>% 
  ggplot(aes(x = n))+
  geom_bar(fill = colors[3]) +
  theme_minimal() +
  ggtitle("Which inflatable duck are you today?") +
  labs(x = "Duck number")

ggplotly(duck)

```

## How are you feeling?

```{r}
confidence <- survey1  %>% 
  rename(n = 4) %>% 
  ggplot(aes(x = n))+
  geom_bar(fill = "#43003F") +
  theme_minimal() +
  ggtitle("What best describes how you feel about having an activity on stats?") +
  labs(x = "Feeling") 

ggplotly(confidence)

```




# Bacon 

"Which of these statements, if true, would convince you/nto eat less/no bacon? Tick all that apply."

```{r}
bacon <- survey1 %>% 
  rename(n = 3) %>% 
  mutate(n = str_replace_all(n, "from 15", "from\n15")) %>% 
  separate_rows(n, sep = ", ") %>% 
  ggplot(aes(x = n)) +
  geom_bar(fill = colors[3]) +
  theme_minimal() +
  labs(x = "") +
  coord_flip()

ggplotly(bacon)

```


# Twitter charts 

"Imagine you run the Twitter for Politician B (red). Which chart will you Tweet?"

```{r, message = F}
twitter <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT_-9_FnNGQm9XO1RMMhc3X2yesFSVojqKPhDFf4SXwCScp9UDrr_0GLgSx1N4w0izpON7y5BkwxtPu/pub?output=csv")


twitter_chart <- twitter %>% 
  rename(n = 2) %>% 
  separate_rows(n, sep = ", ") %>% 
  ggplot(aes(x = n)) +
  geom_bar(fill = colors[3]) +
  theme_minimal() +
  labs(x = "Chart")

ggplotly(twitter_chart)

```
